#!/usr/bin/env php
<?php

ini_set("phar.readonly", "0");

(static function (): void {
    if (\file_exists($autoload = __DIR__ . '/../../autoload.php')) {
        // Is installed via Composer
        include_once $autoload;

        return;
    }

    if (\file_exists($autoload = __DIR__ . '/vendor/autoload.php')) {
        // Is installed locally
        include_once $autoload;

        return;
    }

    \fwrite(
        \STDERR,
        <<<'ERROR'
You need to set up the project dependencies using Composer:
    $ composer install
You can learn all about Composer on https://getcomposer.org/.
ERROR
    );

    throw new RuntimeException('Unable to find the Composer autoloader.');
})();

\SOFe\Pharynx\Main::main();
