name: pharynx
description: "Compile plugin with pharynx"
inputs:
  plugin-dir:
    description: "Directory containing plugin.yml and composer.json"
    default: "${{github.workspace}}"
  composer:
    description: "Whether pharynx should include composer from {plugin-dir}/composer.json"
    default: "true"
  composer-version:
    description: "Composer version to use"
    default: "2.5.5"
  pharynx-version:
    description: "Pharynx version to use"
    default: "latest"
  additional-sources:
    description: "Additional sources other than {plugin-dir}/src, separated by colon, absolute or relative to workspace"
    default: ""
  stage-poggit:
    description: "Stage pharynx output to a new branch for Poggit"
    default: "true"
  additional-assets:
    description: "Additional assets other than LICENSE, .poggit.yml and plugin.yml, specify file per line, works the same as 'git add <pathspec>'"
    default: ""

outputs:
  output-phar:
    description: Absolute path to the phar file compiled
  output-dir:
    description: Absolute path to the directory containing the bundled plugin before archive

runs:
  using: "node16"
  main: "index.js"
